grid_map_topic: /Vehicle/Lidar/GridMap/grid_map

grid_map_visualizations:
  - name: elevation_grid
    type: occupancy_grid
    params:
      layer: occupancyProbability
      data_min: 1.08
      data_max: -0.16
